server:
  port: 8000
  address: 0.0.0.0

spring:
  ai:
    moonshot:
      api-key: sk-6f35Xfr9KyVrgJwKpPjD61Jjljf3UcFQbjuChIVbfZY4Wsn3
      chat:
        options:
          model: moonshot-v1-8k
          temperature: 0.7