server:
  port: 8000
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:postgresql://47.103.151.252:5432/quartz?useUnicode=true&characterEncoding=utf-8&stringtype=unspecified&rewriteBatchedStatements=true
    username: app
    password: app
    hikari:
      maximum-pool-size: 6
      minimum-idle: 5
      connection-test-query: SELECT 1
      connection-init-sql: SELECT 1
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never